ALTER TABLE OMAZON.PRODUCTO ADD RUTA_IMAGEN VARCHAR(100) NOT NULL

ALTER TABLE OMAZON.VENTA DROP COLUMN ID_COMPRA

ALTER TABLE OMAZON.COMPRA ADD ID_VENTA INT NOT NULL

SELECT* FROM OMAZON.COMPRA



ALTER TABLE OMAZON.COMPRA 
ADD CONSTRAINT fk_id_venta_compra
FOREIGN KEY(ID_VENTA)
REFERENCES OMAZON.VENTA(ID_VENTA)

ALTER TABLE OMAZON.COMPRA ALTER COLUMN ID_VENTA INT NULL

ALTER TABLE OMAZON.VENTA ALTER COLUMN MONTO_TOTAL VARCHAR(32) NULL