
-DELETE OMAZON.PRODUCTO_CATEGORIA FROM OMAZON.PRODUCTO_CATEGORIA PC
JOIN OMAZON.PRODUCTO P
ON PC.ID_PRODUCTO= P.ID_PRODUCTO
WHERE P.ID_PROVEEDOR=1 OR P.ID_PROVEEDOR=2 OR P.ID_PROVEEDOR=3



-DELETE FROM OMAZON.PRODUCTO WHERE ID_PROVEEDOR=1
or ID_PROVEEDOR=2
or ID_PROVEEDOR=3
