CREATE PROCEDURE OMAZON.sp_INSERTAR_PRODUCTO_CARRITO
@p_ID_USUARIO INT,
@p_ID_PRODUCTO INT,
@p_CANTIDAD		INT,
@p_SUBTOTAL		VARCHAR(30)
AS
BEGIN 
	INSERT INTO OMAZON.CARRITO_COMPRAS
	(
	 [ID_CLIENTE], [ID_PRODUCTO],[CANTIDAD],[SUB_TOTAL]	
	)
	VALUES
	(
		@p_ID_USUARIO,
		@p_ID_PRODUCTO,
		@p_CANTIDAD,
		@p_SUBTOTAL		
	)

	SELECT 
	'REGISTRADO' AS RESPUESTA
END-- PROCEDURE