CREATE PROCEDURE OMAZON.sp_BUSCAR_PRODUCTO_NOMBRE
@NOMBRE_BUSCAR VARCHAR(32)
AS
BEGIN
	IF EXISTS(SELECT* 
					FROM OMAZON.PRODUCTO P 
					WHERE P.NOMBRE_PRODUCTO LIKE '%'+@NOMBRE_BUSCAR+'%' )
	BEGIN
		SELECT
			P.ID_PRODUCTO,
			P.NOMBRE_PRODUCTO,
			P.PRECIO,
			P.STOCK,
			P.RUTA_IMAGEN,
			C.NOMBRE_CATEGORIA
				FROM OMAZON.PRODUCTO P
				   LEFT JOIN OMAZON.PRODUCTO_CATEGORIA PA
					  ON PA.ID_PRODUCTO=P.ID_PRODUCTO
					   LEFT JOIN OMAZON.CATEGORIA C
						 ON C.ID_CATEGORIA=PA.ID_CATEGORIA
						   WHERE P.NOMBRE_PRODUCTO LIKE '%'+@NOMBRE_BUSCAR+'%'
	END
	ELSE
		BEGIN
		SELECT 'No se han encontrado productos asociados a "'+@NOMBRE_BUSCAR+'"'
		END
END
