ALTER PROCEDURE OMAZON.sp_BUSCAR_PRODUCTO_NOMBRE
@NOMBRE_BUSCAR VARCHAR(32)
AS
BEGIN
	IF EXISTS(SELECT* 
					FROM OMAZON.PRODUCTO P 
					WHERE P.NOMBRE_PRODUCTO LIKE '%'+@NOMBRE_BUSCAR+'%' )
	BEGIN
		SELECT
			P.ID_PRODUCTO,
			P.NOMBRE_PRODUCTO,
			P.PRECIO,
			P.STOCK,
			P.RUTA_IMAGEN,
			C.NOMBRE_CATEGORIA,
			PRO.NOMBRE_PROVEEDOR
				FROM OMAZON.PRODUCTO P
				   LEFT JOIN OMAZON.PRODUCTO_CATEGORIA PA
					  ON PA.ID_PRODUCTO=P.ID_PRODUCTO
					   LEFT JOIN OMAZON.CATEGORIA C
						 ON C.ID_CATEGORIA=PA.ID_CATEGORIA
							LEFT JOIN OMAZON.PROVEEDOR_PRODUCTO PP
								ON P.ID_PRODUCTO = PP.ID_PRODUCTO
									LEFT JOIN OMAZON.PROVEEDOR PRO
										ON PP.ID_PROVEEDOR = PRO.ID_PROVEEDOR
						   WHERE P.NOMBRE_PRODUCTO LIKE '%'+@NOMBRE_BUSCAR+'%'
	END
	ELSE
		BEGIN
		SELECT 'No se han encontrado productos asociados a "'+@NOMBRE_BUSCAR+'"'
		END
END
GO

ALTER PROCEDURE [PRODUCTO].[sp_SELECT_PRODUCTOS]
AS
BEGIN
	SELECT
	P.ID_PRODUCTO,
	P.NOMBRE_PRODUCTO,
	P.PRECIO,
	P.STOCK,
	P.RUTA_IMAGEN,
	C.NOMBRE_CATEGORIA,
	PRO.NOMBRE_PROVEEDOR
		FROM OMAZON.PRODUCTO P
			LEFT JOIN OMAZON.PRODUCTO_CATEGORIA PA
				ON PA.ID_PRODUCTO=P.ID_PRODUCTO
				LEFT JOIN OMAZON.CATEGORIA C
					ON C.ID_CATEGORIA=PA.ID_CATEGORIA
					LEFT JOIN OMAZON.PROVEEDOR_PRODUCTO PP
						ON P.ID_PRODUCTO = PP.ID_PRODUCTO
							LEFT JOIN OMAZON.PROVEEDOR PRO
								ON PP.ID_PROVEEDOR = PRO.ID_PROVEEDOR
END
GO