
ALTER PROCEDURE OMAZON.sp_CREAR_SOLICITUD
@param_clave VARCHAR(50),
@param_firma VARCHAR(32)
AS
BEGIN
	INSERT INTO OMAZON.SOLICITUD_PROVEEDOR (CLAVE,FIRMA) VALUES(@param_clave,@param_firma);
	SELECT 'Se ha enviado la solicitud';
END

ALTER PROCEDURE OMAZON.sp_OBTENER_SOLICITUDES
AS
BEGIN
	SELECT
	ID_SOLICITUD,
	CLAVE,
	FIRMA

	FROM OMAZON.SOLICITUD_PROVEEDOR
END

ALTER PROCEDURE OMAZON.sp_VERIFICAR_VALIDAR_SOLICITUD
@param_clave varchar(50)
AS
BEGIN
IF EXISTS(SELECT* FROM OMAZON.CLAVE_ACCESO WHERE NUMERO_CLAVE=@param_clave)
		BEGIN
			DELETE FROM OMAZON.SOLICITUD_PROVEEDOR WHERE CLAVE=@param_clave
			SELECT ID_PROVEEDOR FROM OMAZON.CLAVE_ACCESO WHERE NUMERO_CLAVE=@param_clave
			---luego la borra
		END
		ELSE
			BEGIN
				SELECT '0'
			END
END

CREATE PROCEDURE OMAZON.sp_BORRAR_SOLICITUD
@param_ID_SOLICITUD INT
AS
BEGIN 
	DELETE FROM OMAZON.SOLICITUD WHERE ID_SOLICITUD=@param_ID_SOLICITUD
END
