
ALTER PROCEDURE OMAZON.sp_CREAR_SOLICITUD
@param_clave VARCHAR(50),
@param_firma VARCHAR(32)
AS
BEGIN
	INSERT INTO OMAZON.SOLICITUD_PROVEEDOR (CLAVE,DETALLES) VALUES(@param_clave,@param_firma);
	SELECT 'Se ha enviado la solicitud';
END

ALTER PROCEDURE OMAZON.sp_OBTENER_SOLICITUDES
AS
BEGIN
	SELECT
	ID_SOLICITUD,
	CLAVE,
	DETALLES

	FROM OMAZON.SOLICITUD_PROVEEDOR
	WHERE ESTADO=0
END

ALTER PROCEDURE OMAZON.sp_VERIFICAR_VALIDAR_SOLICITUD
@param_id varchar(50)
AS
DECLARE @local_clave VARCHAR(50)
DECLARE @local_id_proveedor INT
BEGIN
IF EXISTS
		(SELECT* FROM OMAZON.SOLICITUD_PROVEEDOR WHERE ID_SOLICITUD=@param_id AND ESTADO=0)

		BEGIN

		SET @local_clave= (SELECT CLAVE FROM OMAZON.SOLICITUD_PROVEEDOR WHERE ID_SOLICITUD=@param_id)
			
			IF EXISTS(SELECT* FROM OMAZON.CLAVE_ACCESO WHERE NUMERO_CLAVE=@local_clave)
				BEGIN
					SET @local_id_proveedor=(SELECT ID_PROVEEDOR FROM OMAZON.CLAVE_ACCESO WHERE NUMERO_CLAVE=@local_clave)
				    UPDATE OMAZON.PROVEEDOR SET IS_DELETED=0 WHERE ID_PROVEEDOR=@local_id_proveedor
					UPDATE OMAZON.SOLICITUD_PROVEEDOR SET ESTADO=1 WHERE ID_SOLICITUD=@param_id
					SELECT @local_id_proveedor
				END
			ELSE
				BEGIN
				UPDATE OMAZON.SOLICITUD_PROVEEDOR SET ESTADO=2 WHERE ID_SOLICITUD=@param_id
				SELECT '0'

				END
			---luego la borra
		END
		ELSE
			BEGIN
				SELECT '-1'
			END
END

ALTER PROCEDURE OMAZON.sp_BORRAR_SOLICITUD
@param_ID_SOLICITUD INT
AS
BEGIN 
	UPDATE OMAZON.SOLICITUD_PROVEEDOR SET ESTADO=-1 WHERE ID_SOLICITUD=@param_ID_SOLICITUD
END
