
CREATE PROCEDURE OMAZON.sp_CREAR_SOLICITUD
@p_clave VARCHAR(50),
@p_firma VARCHAR(32)
AS
BEGIN
	INSERT INTO OMAZON.SOLICITUD (CLAVE,FIRMA) VALUES(@p_clave,@p_firma)
END

ALTER PROCEDURE OMAZON.sp_OBTENER_SOLICITUDES
AS
BEGIN
	SELECT
	ID_SOLICITUD,
	CLAVE,
	FIRMA

	FROM OMAZON.SOLICITUD_PROVEEDOR
END

ALTER PROCEDURE OMAZON.sp_VERIFICAR_VALIDAR_SOLICITUD
@param_clave varchar(50)
AS
BEGIN
IF EXISTS(SELECT* FROM OMAZON.CLAVE_ACCESO WHERE NUMERO_CLAVE=@param_clave)
		BEGIN
			SELECT ID_PROVEEDOR FROM OMAZON.CLAVE_ACCESO WHERE NUMERO_CLAVE=@param_clave
			---luego la borra
			DELETE FROM OMAZON.CLAVE_ACCESO WHERE NUMERO_CLAVE=@param_clave
		END
		ELSE
			BEGIN
				SELECT '0'
			END
END

CREATE PROCEDURE OMAZON.sp_BORRAR_SOLICITUD
@param_ID_SOLICITUD INT
AS
BEGIN 
	DELETE FROM OMAZON.SOLICITUD WHERE ID_SOLICITUD=@param_ID_SOLICITUD
END
